export const OPEN_MODAL_ADD_DOCUMENT = 'OPEN_MODAL_ADD_DOCUMENT'
export const CLOSE_MODAL_ADD_DOCUMENT = 'CLOSE_MODAL_ADD_DOCUMENT'

export const OPEN_MODAL_FILE_ACTION = 'OPEN_MODAL_FILE_ACTION'
export const CLOSE_MODAL_FILE_ACTION = 'CLOSE_MODAL_FILE_ACTION'

export const OPEN_MODAL_FOLDER_ACTION = 'OPEN_MODAL_FOLDER_ACTION'
export const CLOSE_MODAL_FOLDER_ACTION = 'CLOSE_MODAL_FOLDER_ACTION'

export const OPEN_MODAL_CREATE_FOLDER = 'OPEN_MODAL_CREATE_FOLDER'
export const CLOSE_MODAL_CREATE_FOLDER = 'CLOSE_MODAL_CREATE_FOLDER'

export const OPEN_MODAL_ADD_FILE_INFO = 'OPEN_MODAL_ADD_FILE_INFO'
export const CLOSE_MODAL_ADD_FILE_INFO = 'CLOSE_MODAL_ADD_FILE_INFO'